name: Setup Poetry
description: Installs Poetry into a Python environment
inputs:
  version:
    description: The version of Poetry to install (defaults to the most recent).
  preview:
    description: Whether or not to install the preview version of Poetry (defaults to false).
    default: 'false'
  create_virtualenvs:
    description: Whether or not Poetery should create a new virtualenv when installing your project (defaults to false).
    default: 'false'
runs:
  using: node16
  main: dist/index.js

