name: "units-test"

on:
  pull_request:
  push:

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test

  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - '3.10'
          - 3.11
          - 'pypy-3.8'
        exclude:
          - platform: windows-latest
            python-version: 'pypy-3.8'
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./
      - run: poetry self --version
